import { ColumnDetails } from "./Column.details.interface.js";

export const DEFAULT_PROPERTIES: Record<string, Partial<ColumnDetails>> = {
    id: {
      field: "id",
      type: "number",
      length: "",
      isPrimary: true,
      isGenerated: true,
      default: null,
      isUnique: true,
      nullable: false,
    },
    createdAt: {
      field: "createdAt",
      type: "timestamp",
      length: "",
      isPrimary: false,
      isGenerated: false,
      default: "now()",
      isUnique: false,
      nullable: false,
    },
    updatedAt: {
      field: "updatedAt",
      type: "timestamp",
      length: "",
      isPrimary: false,
      isGenerated: false,
      default: "now()",
      isUnique: false,
      nullable: false,
    },
    deletedAt: {
      field: "deletedAt",
      type: "timestamp",
      length: "",
      isPrimary: false,
      isGenerated: false,
      default: null,
      isUnique: false,
      nullable: true,
    },
    field: {
      field: "field",
      type: "varchar",
      length: "255",
      isPrimary: false,
      isGenerated: false,
      default: null,
      isUnique: false,
      nullable: false,
    },
      email: {
          field: "email",
          type: "varchar",
          length: "255",
          isPrimary: false,
          isGenerated: false,
          default: null,
          isUnique: true,
          nullable: false,
      },
      password: {
          field: "password",
          type: "varchar",
          length: "255",
          isPrimary: false,
          isGenerated: false,
          default: null,
          isUnique: false,
          nullable: false,
      },
      
  };
  